language: python
python:
  - "2.7"
services: mongodb
# Apply only on main branches
branches:
  except:
    - /^feature.*$/
# command to install dependencies with mobyle2.lib on develop
install:
  - "pip install paste pastedeploy pastescript py-bcrypt mongokit mf pygeoip uuid"
  - "pip install git+https://github.com/mobyle2/mobyle2.lib.git@develop#egg=mobyle.lib"
  - "pip install -r requirements.txt"
  - "python setup.py install"
# command to run tests
script: nosetests


